version: "3.8"

services:
  backend:
    build: ./backend
    container_name: pizzaria-backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - pizzaria-network

  frontend:
    build: ./frontend
    container_name: pizzaria-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html
    networks:
      - pizzaria-network

networks:
  pizzaria-network:
    driver: bridge
