on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checagem
        run: | # O 'run' precisa de um comando abaixo
          echo "Fazendo a checagem"
